In [48]:
import yfinance as yf

from ipywidgets import interact_manual

from mplchart.chart import Chart
from mplchart.indicators import SMA, RSI, MACD, PPO
from mplchart.primitives import Volume, Candlesticks, Pane


def get_prices(ticker, period="max"):
    prices = yf.download(ticker, period=period, multi_level_index=False, progress=False)
    return prices.rename(columns=str.lower).rename_axis(index=str.lower)

In [ ]:
indicators = [Candlesticks(), SMA(50), SMA(200), Volume(), Pane("above"), RSI(), Pane("below"), PPO()]


@interact_manual(ticker="AAPL", max_bars=250)
def draw_chart(ticker, max_bars=250):
    prices = get_prices(ticker)
    chart = Chart(prices, title=ticker, max_bars=max_bars, normalize=True)
    chart.plot(indicators)

interactive(children=(Text(value='AAPL', continuous_update=False, description='ticker'), IntSlider(value=250, …